server:
  port: 17070
  servlet:
    context-path: /
    session:
      timeout: Pt4h
      cookie:
        name: JSESSIONID_BW

spring:
  application:
    name: Big Whale
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_whale?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password:
    tomcat:
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
      validation-query: select 1
  profiles:
    active: dev # load application-dev.yml
  data:
    rest:
      returnBodyOnCreate: true
      returnBodyOnUpdate: true
  jackson:
    timeZone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      fail-on-empty-beans: false
      write-null-map-values: true
      write-empty-json-arrays: true
  thymeleaf:
    mode: LEGACYHTML5
  servlet:
    multipart:
      enabled: true
      max-file-size: 200Mb
      max-request-size: 200Mb
  quartz:
    job-store-type: memory # jdbc延迟过高，统一使用memory，放弃分布式
    properties:
      org:
        quartz:
          scheduler:
            instanceName: BigWhaleScheduler
            instanceId: AUTO
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 100
            threadPriority: 5
          jobStore:
            misfireThreshold: 120000

logging:
  level:
    com.ctrip.framework.apollo.internals.RemoteConfigLongPollService: error
    com.ctrip.framework.apollo.internals.RemoteConfigRepository: error

apollo:
  bootstrap:
    enabled: true
